"""hackathon_stats

Revision ID: efd1ccf3101d
Revises: c13d685e63fc
Create Date: 2026-09-29 22:24:14.398334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efd1ccf3101d'
down_revision = 'c13d685e63fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hackathons_won', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('hackathons_participated', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('hackathons_participated')
        batch_op.drop_column('hackathons_won')

    # ### end Alembic commands ###
